name: libvips
version: v8.10.5
grade: stable
summary: A precompiled snap for libvips/libvips
description: >
  A precompiled snap for libvips/libvips
base: core18
confinement: strict

parts:
  libvips:
    plugin: nil
    build-packages:
      - git
      - sqlite3
      - libsqlite3-dev
      - build-essential
      - automake
      - libtool
      - swig
      - libxml2-dev
      - libfftw3-dev
      - libmagickwand-dev
      - libopenexr-dev
      - liborc-0.4-0
      - gobject-introspection
      - libgsf-1-dev
      - libglib2.0-dev
      - liborc-0.4-dev
      - gtk-doc-tools
      - libopenslide-dev
      - libmatio-dev
      - libgif-dev
      - python-gi-dev
      - libgirepository1.0-dev
    source: .
    build-environment:
      - VIPSHOME: "/usr/local"
      - PATH: "$VIPSHOME/bin:$SNAPCRAFT_PART_BUILD/node_modules/.bin:$SNAPCRAFT_PART_BUILD/../npm/bin:$PATH"
      - LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$VIPSHOME/lib"
      - PKG_CONFIG_PATH: "$PKG_CONFIG_PATH:$VIPSHOME/lib/pkgconfig"
      - PYTHONPATH: "$VIPSHOME/lib/python3.6/site-packages"
    override-build: |
      git clone --depth 1 --branch v8.10.5 https://github.com/libvips/libvips.git
      cd libvips && ./autogen.sh
      make -j$(nproc) && make install
    stage-packages:
      - libaec0
      - libcairo2
      - libcroco3
      - libdatrie1
      - libexif12
      - libfftw3-double3
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgif7
      - libgomp1
      - libgraphite2-3
      - libgsf-1-114
      - libharfbuzz0b
      - libhdf5-100
      - libicu60
      - libilmbase12
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - liblqr-1-0
      - libltdl7
      - libmagickcore-6.q16-3
      - libmatio4
      - libopenexr22
      - libopenjp2-7
      - libopenslide0
      - liborc-0.4-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - librsvg2-2
      - libsz2
      - libthai0
      - libtiff5
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxml2
      - libxrender1
